### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by Qubik65536** [FOSScope/Toolkit#3]
This issue contains the development roadmap for this project.

The GitHub Project https://github.com/orgs/FOSScope/projects/1 is used to display and organize issues.

Each item is a feature node to implement, and the username of maintainer/developer who proposed the feature.

## 工具箱配置

- [X] [FEATURE] 基于 GitHub Token 的用户配置 (@Cubik65536)
- [ ] [FEATURE] 基于 GitHub Application "Login with GitHub" 的用户配置 (@Cubik65536)
- [X] [FEATURE] 贡献者仓库的配置 (@Cubik65536)

### 杂项

- [ ] #20 (@Cubik65536)

### Stage 1：选题

- [X] [FEATURE] HTML 转 markdown (@Cubik65536)
- [X] [FEATURE] HTML 过滤 (@ cysnies)
- [ ] #25 (@Cubik65536)
- [ ] #10 (@cysnies)
- [ ] [FEATURE] 选题时自动将特殊格式（如外部文章引用、强调块等）转换为主题支持的标签块 (@cys2004)
	- [ ] [FEATURE] 自动的 It's FOSS 站特殊格式转文章源文件标签块规则
- [x] #6 (@Cubik65536)
- [x] #5 (@Cubik65536)
- [x] #8 (@Cubik65536)
- [x] #9 (@Cubik65536)
- [x] #14 (@Cubik65536)
- [x] #12 (@Cubik65536)

### Stage 2：翻译

- [ ] #22 (@Cubik65536)
- [ ] [FEATURE] 自动化译文提交流程，允许贡献者直接看到已被其申领的译文，并在翻译完成后自动提交并提起 PR (@Cubik65536)
- [ ] [FEATURE] 在译文提交前，使用 [pangu.rs](https://crates.io/crates/pangu) 自动进行 Markdown 格式化 (@Cubik65536)
- [ ] [FEATURE] 自动检测翻译文章中的格式错误并提供快速修改功能 (@cysnies)

### Stage 3：校对

_暂无_

### Stage 4：发布

_暂无_

## 前端

_暂无_

## 其他

- [X] [DOCS] 仓库规则文件的定义 (@Cubik65536)
- [x] #4 (@Cubik65536)
- [x] #17 (@Cubik65536)
- [ ] 增加 issue 以及 pull request 模板 (@Cubik65536)
- [ ] 增加 GitHub Action 编译 CI (@Cubik65536)
- [ ] 增加 CoC & Contribution Guide (@Cubik65536)
